spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: 'jdbc:mariadb://localhost:3306/concert'
    username: username
    password: password

  data:
    redis:
      host: localhost
      port: 6379
