spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: 'jdbc:tc:mariadb:10.11://concert'
    username: username
    password: password

  data:
    redis:
      host: localhost
      port: 6379
