spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./h2db'
    username: username
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console
