spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: 'jdbc:tc:mariadb:10.11://concert'
    username: username
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console
