version: "3.7"

name: concert-k6-client

services:
  k6:
    image: grafana/k6:latest
    entrypoint: ["k6", "run", "/scripts/script.js"]
    network_mode: host
    environment:
      - K6_OUT=influxdb=http://localhost:8086/myk6db
    volumes:
      - ./script.js:/scripts/script.js
